services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: burim-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
  product-db:
    image: postgres:16-alpine
    container_name: burim-product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5433:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data

  review-db:
    image: postgres:16-alpine
    container_name: burim-review-db
    environment:
      POSTGRES_DB: review_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5434:5432"
    volumes:
      - review_postgres_data:/var/lib/postgresql/data

volumes:
  product_postgres_data:
  review_postgres_data: